version: '3'
services:
  web:
    build: ./web
    ports:
     - "5001-5003:80"
    volumes:
     - /root/nginx:/usr/share/nginx/html
    deploy:
      replicas: 3
  
  app:
    build: ./app
    ports:
      - "5004:80"

  cache_balancer:
    build: ./cache_balancer
    ports:
     - "5000:80"
    depends_on:
     - web
     - app

  redirect:
    build: ./redirect
    ports:
     - "80:80"
    depends_on:
    - cache_balancer
